### ISSUE TITLE
Code Review Session #2

### ISSUE THREAD

**Issue by ptahdunbar** [Shonte/shontedeveaux.com#2]
# TODO

- [ ] Validate HTML markup with https://validator.w3.org/
- [ ] Apply recommendations and improvements with https://developers.google.com/speed/pagespeed/insights/

## Current Results:
- 67 / 100 Speed (Mobile)
- 78 / 100 User Experience (Mobile)
- 75 / 100 (Desktop)

-----
- [Run pagespeed](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fshontedeveaux.com&tab=mobile)
- [Run W3C HTML Validator](https://validator.w3.org/nu/?doc=http%3A%2F%2Fshontedeveaux.com%2F)

**Comment by Shonte** [comment]
* [ ] Page Insights pass with https://search.google.com/search-console/mobile-friendly

**Comment by Shonte** [comment]
I fixed 16/22 warnings from CSS lint. One line is giving me 6 warnings. For some reason, I need help solving this one. @ptahdunbar
